In [1]:
import numpy as np
import json
import matplotlib.pyplot as plt
from glob import glob
import earthpy as epy
import earthpy.spatial as es
import earthpy.plot as ep
import rasterio as rio
from matplotlib.colors import ListedColormap
import plotly.graph_objects as go
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import copy

In [2]:
# path = "/media/ankith/New Volume"
path = "/media/ankith/New Volume/BigEarthNet-S2-v1.0/BigEarthNet-v1.0"

import os
dir_list = os.listdir(path)
# dir_list = dir_list[:2]
dir_len = len(dir_list)
print(dir_len)
dir_list

590326


['S2A_MSIL2A_20170613T101031_0_45',
 'S2A_MSIL2A_20170613T101031_0_46',
 'S2A_MSIL2A_20170613T101031_0_47',
 'S2A_MSIL2A_20170613T101031_0_48',
 'S2A_MSIL2A_20170613T101031_0_49',
 'S2A_MSIL2A_20170613T101031_0_50',
 'S2A_MSIL2A_20170613T101031_0_51',
 'S2A_MSIL2A_20170613T101031_0_52',
 'S2A_MSIL2A_20170613T101031_0_53',
 'S2A_MSIL2A_20170613T101031_0_54',
 'S2A_MSIL2A_20170613T101031_0_55',
 'S2A_MSIL2A_20170613T101031_0_56',
 'S2A_MSIL2A_20170613T101031_0_57',
 'S2A_MSIL2A_20170613T101031_0_58',
 'S2A_MSIL2A_20170613T101031_0_59',
 'S2B_MSIL2A_20170906T101019_42_64',
 'S2B_MSIL2A_20170906T101019_42_65',
 'S2B_MSIL2A_20170906T101019_42_66',
 'S2B_MSIL2A_20170906T101019_42_67',
 'S2B_MSIL2A_20170906T101019_42_68',
 'S2B_MSIL2A_20170906T101019_42_69',
 'S2B_MSIL2A_20170906T101019_42_7',
 'S2B_MSIL2A_20170906T101019_42_70',
 'S2B_MSIL2A_20170906T101019_42_71',
 'S2B_MSIL2A_20170906T101019_42_72',
 'S2B_MSIL2A_20170906T101019_42_73',
 'S2B_MSIL2A_20170906T101019_42_74',
 'S2B_MSIL2A_2017

In [3]:
rdm_array = np.load("np_array.npy")
print(rdm_array[0])

[[[ 396  287  171 ...  372  249   56]
  [ 442  350  176 ...  408  347  215]
  [ 297  300  318 ...  507  678  583]
  ...
  [  38  109  126 ... 1009  920  607]
  [ 162  114  134 ...  621  240   83]
  [ 195  169  144 ...  102   32   39]]

 [[ 757  628  366 ...  733  498  232]
  [ 763  674  461 ...  819  718  473]
  [ 567  554  588 ...  964 1126 1016]
  ...
  [ 170  280  335 ... 1507 1478 1230]
  [ 299  346  346 ... 1202  655  415]
  [ 431  362  266 ...  388  281  249]]

 [[ 759  710  355 ...  730  468  274]
  [ 841  742  462 ...  828  675  480]
  [ 609  673  702 ...  914 1304 1026]
  ...
  [ 225  353  396 ... 2009 1843 1464]
  [ 414  399  431 ... 1355  748  460]
  [ 499  455  452 ...  435  239  243]]]


In [30]:
print(rdm_array.shape)

(10000, 3, 120, 120)


In [50]:
print(rdm_array[0]/255.)

[[[1.55294118 1.1254902  0.67058824 ... 1.45882353 0.97647059 0.21960784]
  [1.73333333 1.37254902 0.69019608 ... 1.6        1.36078431 0.84313725]
  [1.16470588 1.17647059 1.24705882 ... 1.98823529 2.65882353 2.28627451]
  ...
  [0.14901961 0.42745098 0.49411765 ... 3.95686275 3.60784314 2.38039216]
  [0.63529412 0.44705882 0.5254902  ... 2.43529412 0.94117647 0.3254902 ]
  [0.76470588 0.6627451  0.56470588 ... 0.4        0.1254902  0.15294118]]

 [[2.96862745 2.4627451  1.43529412 ... 2.8745098  1.95294118 0.90980392]
  [2.99215686 2.64313725 1.80784314 ... 3.21176471 2.81568627 1.85490196]
  [2.22352941 2.17254902 2.30588235 ... 3.78039216 4.41568627 3.98431373]
  ...
  [0.66666667 1.09803922 1.31372549 ... 5.90980392 5.79607843 4.82352941]
  [1.17254902 1.35686275 1.35686275 ... 4.71372549 2.56862745 1.62745098]
  [1.69019608 1.41960784 1.04313725 ... 1.52156863 1.10196078 0.97647059]]

 [[2.97647059 2.78431373 1.39215686 ... 2.8627451  1.83529412 1.0745098 ]
  [3.29803922 2.909803

In [11]:
path_array = np.load("rndm_dir.npy")
path_array[:5]

array(['S2A_MSIL2A_20171221T112501_84_49',
       'S2A_MSIL2A_20171221T112501_3_4',
       'S2A_MSIL2A_20180413T95032_39_19',
       'S2B_MSIL2A_20171206T094349_60_5',
       'S2A_MSIL2A_20180506T100031_22_48'], dtype='<U32')

In [32]:
# labels_list = []
# for i in path_array[:10000]:
#     folder_path = i
#     json_path = glob(path+"/"+folder_path+"/*labels*.json")
#     data = json.load(open(json_path[0]))
#     labels_list.append(np.array(data["labels"]))
# print(len(labels_list))

10000


In [36]:
# print(type(labels_list))
# print(type(labels_list[0]))

<class 'list'>
<class 'numpy.ndarray'>


In [39]:
# labels_list = np.array(labels_list, dtype=object)
# labels_list.shape

(10000,)

In [40]:
# print(type(labels_list))
# print(type(labels_list[0]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [41]:
# np.save("np_labels", labels_list)

In [46]:
labels_list = np.load("np_labels.npy",allow_pickle=True)
print(labels_list[0])
print(labels_list.shape)

['Vineyards' 'Olive groves' 'Agro-forestry areas'
 'Transitional woodland/shrub' 'Water bodies']
(10000,)


In [44]:
l = []
for i in labels_list:
    for j in i:
        l.append(j)
li = l.copy()
l = np.array(l)
uni = np.unique(l)
print(uni.shape)
# print(uni)

(43,)


In [47]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import copy

In [63]:
# # 0,len(rdm_array)
# for i in range(1):
#     test = rdm_array[i].resize(3,112,112)
# print(test.shape)
import cv2
test = rdm_array[0]

In [72]:
res = cv2.resize(test, dsize=(112, 112), interpolation=cv2.INTER_AREA)
print(res.shape)

(112, 112, 120)


In [48]:
model = models.resnet18(pretrained=False)
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  